server:
  port: 8080
spring:
  config:
    location: classpath:/database.yml
  datasource:
    url: jdbc:mysql://localhost:3306/chat_jwt
    username: root
    password: 12345
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    root: DEBUG